GaripSozluk.WebApp/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GaripSozluk.WebApp.Controllers
{
    public class HeaderController : Controller
    {
        private readonly IHeaderCategoryService _headerCategoryService;
        private readonly IHeaderService _headerService;

        public HeaderController(IHeaderCategoryService headerCategoryService, IHeaderService headerService)
        {
            _headerCategoryService = headerCategoryService;
            _headerService = headerService;
        }

        [Authorize]
        public IActionResult CreateHeader(int id)
        {
            ViewBag.HeaderCategoryList = _headerCategoryService.GetHeadersSelect(id); //kategorileri çekiyor
            ViewBag.Headers = _headerService.GetAll();
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult CreateHeader(HeaderVM model)
        {
            if (ModelState.IsValid)
            {
                var user = HttpContext.User;
                var userId = int.Parse( user.Claims.ToList().Where(x=>x.Type==ClaimTypes.NameIdentifier).FirstOrDefault().Value);
                model.UserId = userId;
                _headerService.AddHeader(model);
            }
            ViewBag.HeaderCategoryList = _headerCategoryService.HeaderCategoryList();
            ViewBag.Headers = _headerService.GetAll();
            return View();
        }

        public IActionResult GetCategoryHeader(int CategoryID,int id)
        {
            //ViewBag.Headers = _headerService.GetAllHeaderByCategoryId(id);
            //ViewBag.HeaderCategoryList = _headerCategoryService.HeaderCategoryList();
            ViewBag.Headers = _headerService.GetAll();
            ViewBag.HeaderByCategory = _headerService.GetAllHeaderByCategoryId(CategoryID);
            ViewBag.HeaderCategoryList = _headerCategoryService.GetHeadersSelect(id); //kategorileri Çekiyor
            return View();
        }


    }
}

GaripSozluk.WebApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GaripSozluk.WebApp.Controllers
{
    public class PostController : Controller
    {
        private readonly ILogger<PostController> _logger;
        private readonly IHeaderCategoryService _headerCategoryService;
        private readonly IHeaderService _headerService;
        private readonly IPostService _postService;

        public PostController(ILogger<PostController> logger, IHeaderService headerService, IHeaderCategoryService headerCategoryService, IPostService postService)
        {
            _headerCategoryService = headerCategoryService;
            _logger = logger;
            _headerService = headerService;
            _postService = postService;
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddPost(int CategoryID, int id, int HeaderId, PostVM model)
        {
            var headerId = HttpContext.Request.Query["HeaderId"].Count  > 0 ? int.Parse(HttpContext.Request.Query["HeaderId"]) : 0;
            if (ModelState.IsValid)
            {
                var user = HttpContext.User;
                var userId = int.Parse(user.Claims.ToList().Where(x => x.Type == ClaimTypes.NameIdentifier).FirstOrDefault().Value);
                model.UserId = userId;
                model.HeaderId = headerId;
                _postService.AddPost(model);
            }

            return View();
        }

        [Authorize]
        public IActionResult AddPost(int CategoryID, int id, int headerId)
        {
            //ViewBag.HeaderByCategory = _headerService.GetAllHeaderByCategoryId(CategoryID);
            //ViewBag.HeaderCategoryList = _headerCategoryService.GetHeadersSelect(id); //Kategorileri Çekiyor
            //ViewBag.HeaderId = headerId;

            return View(new PostVM() { HeaderId = headerId });
        }

        public IActionResult GetPost(int CategoryId, int id, int HeaderId)
        {
            var query = _postService.GetAllPostByHeaderId(HeaderId);
            ViewBag.GetPostsByHeaderId = query;
            ViewBag.HeaderByCategory = _headerService.GetAllHeaderByCategoryId(CategoryId);
            ViewBag.HeaderCategoryList = _headerCategoryService.GetHeadersSelect(id); //Kategorileri Çekiyor
            return View();
        }




    }
}

GaripSozluk.WebApp/Controllers/RandomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GaripSozluk.WebApp.Controllers
{
    public class RandomController : Controller
    {
        private readonly IPostService _postService;

        public RandomController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult RandomHeader(int HeaderId)
        {
            ViewBag.RandomHeader = _postService.GetAllPostByHeaderId(HeaderId);
            return View();
        }
    }
}

GaripSozluk.WebApp/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GaripSozluk.Business.Interfaces;
using GaripSozluk.Common.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GaripSozluk.WebApp.Controllers
{
    public class SearchController : Controller
    {
        private readonly IHeaderCategoryService _headerCategoryService;
        private readonly ISearchService _searchService;

        public SearchController(ISearchService searchService, IHeaderCategoryService headerCategoryService)
        {
            _headerCategoryService = headerCategoryService;
            _searchService = searchService;
        }

        public IActionResult SearchHeader(SearchVM model,string text)
        {
            model.SearchText = text;
            ViewBag.SearchResult = _searchService.SearchHeader(model.SearchText);
            return View();
        }

        public IActionResult DetailSearchHeader(int id)
        {
            ViewBag.HeaderCategoryList = _headerCategoryService.GetHeadersSelect(id);
            return View();
        }

        [HttpPost]
        public IActionResult DetailSearchHeader(string text,DateTime create, int categoryid)
        {
            ViewBag.DetailSearchResult = _searchService.DetailSearchHeader(text, create,categoryid);
            return View();
        }

    }
}

GaripSozluk.WebApp/Views/Shared/_Layout.cshtml
@{ 
    Random rastgele = new Random();
    int Rasgele = rastgele.Next(2, 7);
}


@*@model IQueryable<GaripSozluk.Data.Domain.Header>*@
<!DOCTYPE html>
<html lang="tr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Güzel Sözlük</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">

        <!-- SOL MENÜ BAŞLANGIÇ -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
                <a class="sidebar-brand brand-logo" href="/home/index"><img src="~/images/logo.png" alt="logo" /></a>
                <a class="sidebar-brand brand-logo-mini" href="/home/index"><img src="~/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <ul class="nav ">
                <li class="nav-item profile">
                    <div class="profile-desc">
                        <div class="profile-pic">
                            <div class="count-indicator">
                                <img class="img-xs rounded-circle " src="~/images/faces/861643-200.png" alt="">
                            </div>
                            <div class="profile-name">
                                <h5 class="mb-0 font-weight-normal">Kategoriler</h5>
                            </div>
                        </div>
                        <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>

                        <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                            @if (ViewBag.HeaderCategoryList != null)
                            {
                                @foreach (var item in ViewBag.HeaderCategoryList)
                                {
                                    <a class="dropdown-item preview-item"asp-area="" asp-controller="Header" asp-action="GetCategoryHeader" asp-route-CategoryID="@item.Value">
                                        <div class="preview-item-content">
                                            <p class="preview-subject ellipsis mb-1 text-small">@item.Text</p>
                                        </div>
                                    </a>
                                }
                            }
                        </div>
                    </div>
                </li>

                <li class="nav-item nav-category">
                    <span class="nav-link text-light">En Yeniler</span>
                </li>
                @if (ViewBag.HeaderByCategory != null)
                {
                    @foreach (var item in ViewBag.HeaderByCategory)
                    {
                        <li class="nav-item menu-items nav-category">
                            <p><a asp-route-HeaderId="@item.Id" asp-controller="Post" asp-action="GetPost">@item.Title</a></p>
                        </li>
                    }
                }
            </ul>
        </nav>
        <!-- SOL MENÜ BİTİŞ -->

        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_navbar.html -->
            <nav class="navbar p-0 fixed-top d-flex flex-row">
                <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
                    <a class="navbar-brand brand-logo-mini" href="/home/index"><img src="~/images/logo-mini.svg" alt="logo" /></a>
                </div>
                <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">

                    <ul class="navbar-nav w-100">
                        <li class="nav-item w-100">
                            <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search" method="post" asp-controller="search" asp-action="SearchHeader">
                                <input type="text" class="form-control" placeholder="Başlık Arayın...." name="text">
                                <button type="submit" class="btn btn-primary btn-rounded btn-fw align-self-md-center">Başlık Ara</button>
                                <a type="button" class="btn btn-secondary btn-rounded btn-fw align-self-md-center" asp-controller="Search" asp-action="DetailSearchHeader">Detaylı Ara</a>

                                <a type="button" class="btn btn-warning btn-rounded btn-fw align-self-md-center" asp-controller="Random" asp-action="RandomHeader" asp-route-HeaderId="@Rasgele">Rastgele</a>
                            </form>
                        </li>
                    </ul>

                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item dropdown d-none d-lg-block">
                            <a class="nav-link btn btn-success create-new-button" asp-controller="Header" asp-action="CreateHeader">+ Yeni Başlık Oluşturun</a>

                            <!--Bildirimler Bölümü-->

                        <li class="nav-item dropdown border-left">
                            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                                <i class="mdi mdi-bell"></i>
                                <span class="count bg-danger"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                                <h6 class="p-3 mb-0">Bildirimler</h6>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item preview-item">
                                    <div class="preview-thumbnail">
                                        <!--   <div class="preview-icon bg-dark rounded-circle">
                            <i class="mdi mdi-text text-success"></i>
                          </div>
                        </div>
                        <div class="preview-item-content">
                         <p class="preview-subject mb-1">En Çok Beğenilen Entry</p> -->
                                        <!--       <p class="text-muted "> Nasıl HTML Yazamıyorum Oynat Bakalım </p>eğer burada entryi kısaltmak istiyorsan ellipsis mb-0    -->
                                    </div>

                                </a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                                <div class="navbar-profile">

                                    <p class="mb-0 d-none d-sm-block navbar-profile-name">Alper Temel</p>
                                    <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                                <h6 class="p-3 mb-0">Profil</h6>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item preview-item">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-dark rounded-circle">
                                            <i class="mdi mdi-settings text-success"></i>
                                        </div>
                                    </div>
                                    <div class="preview-item-content">
                                        <p class="preview-subject mb-1">Hesap Ayarları</p>
                                    </div>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item preview-item">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-dark rounded-circle">
                                            <i class="mdi mdi-logout text-danger"></i>
                                        </div>
                                    </div>
                                    <div class="preview-item-content">
                                        <p class="preview-subject mb-1">Çıkış Yap</p>
                                    </div>
                                </a>
                            </div>
                        </li>

                    </ul>
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                        <span class="mdi mdi-format-line-spacing"></span>
                    </button>
</nav>
            <!-- partial -->
            <div class="main-panel">

                <div class="content-wrapper">
                    <div class="row">
                        @RenderBody()

                    </div>
                </div>

                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 <a href="http://www.alpertemel.com/" target="_blank">AlperTemel</a>. All rights reserved.</span>
                        <span class="text-muted float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
            </div>

            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/js/off-canvas.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/misc.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <!-- End custom js for this page -->
    @RenderSection("Scripts", required: false)
</body>
</html>